name: Build and push docker images
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_core:
    name: Build image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      - name: Build and push the image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./Dockerfile
          repository: msm2e4d534d/itsec-re
          tags: ${{ github.sha }}-${{ steps.date.outputs.date }}
          push: ${{ github.event_name == 'push' }}
